Simplify or remove several package.json scripts (#38931)
* Remove the analyze-css NPM script

Finishes the removal started in #27979.

* Update clean scripts: paths of generated files, simplify how they are invoked

Updates the paths of generated files to remove (`server/` to `client/server/`), use
`run-s` to run all `clean:*` scripts at once.

* Update path to stats.json file in whybundled script

* Validate fallback build in a separate script

Makes lines in `package.json` shorter 🙂

* Fix the NODE_ARGS argument in the start-build scripts

`node NODE_ARGS=...` is an error that fails the script invocation:
```
Error: Cannot find module '/Users/jsnajdr/src/wp-desktop/calypso/NODE_ARGS=--max_old_space_size=8192'
```
We want to invoke `node` with `$NODE_ARGS` arguments and supply a default.

* Eliminate the need for setting NODE_PATH when building or running Calypso

It was needed only to `require` two specific files (webpack config for webpack dev server
and search index for devdocs). Updated the webpack `externals` definition to remove that
need.

* Update path to stats.json file in analyze-bundles script

* Consolidate setting max_old_space_size to the build-client scripts that runs webpack

* Remove duplication from build-client and start-build tasks by using cross-env and a *-do subtask

* Settle on PROGRESS=true as the truth marker

* Remove cross-env-shell from start-build-do, as it doesn't set any env vars