Package "page-pattern-modal": publishing to npm (#92871)
* Fix for error TS7016: Could not find a declaration file for module '@automattic/calypso-config'

* Update version and fix command not found: copy-assets

* Run copy-assets command globally

* Fix for could not find a declaration file for module '@automattic/calypso-build'

* Bump version

* Fix npm publish errors for the dependency @automattic/onboarding

* Remove unused dependency

* Bump version

* Update yarn lock file

* Fix styles when package is imported

* Bump version

* Revert styles fix

* Bump version