Store Promotions: Create/Update from edit state (#18525)
* Store Promotions: Add selectors for edit states

This adds selectors to get promotion edits, edits overlaid on top of the
existing promotions, and the currently editing promotion.

* Store Promotions: Add selectors for edit states

This adds selectors to get promotion edits, edits overlaid on top of the
existing promotions, and the currently editing promotion.

* Store Promotions: Add selectors for edit states

This adds selectors to get promotion edits, edits overlaid on top of the
existing promotions, and the currently editing promotion.

* Store Promotions: Adjust test code

This propagates the test fix up to another PR

* Store Promotions: Adjust test code

This propagates the test fix up to another PR

* Store Promotions: Adjust test code

This propagates the test fix up to another PR

* Store Promotions: Create/Update from edit state

This hooks up the save actions to create/update/delete promotion
elements.

* Promotions: Adjust code for create/update/list

This updates several things:
1. Sets a derivitive promotion id, p<id> for products, c<id> for
coupons. This makes finding promotions easier between page loads.
2. Changes all timestamps to local instead of GMT. The WooCommerce API
doesn't allow the _gmt timestamps to be set directly, so we have to use
local time.
3. Allows product sales to be moved to another product. It didn't take
much and was easier than disabling the list.
4. Disables changing an existing promotion from a coupon to a sale or
vice versa.
5. Adds an extra `json: true` parameter to body for POST requests
through the wpcom proxy (needed for coupon operations)
6. Smaller miscellanous fixes

* Promotions: Force coupon deletes

When I try to not force a delete, and try to allow trashing, I get this
error: `Error: The shop_coupon does not support trashing.` even though
coupons can be trashed via the wp-admin page. So for now, we delete
permanently.

* Promotion edit: Add boolean checks for form type

This adds actual boolean checks to ensure the right options are enabled
for the selector on an existing promotion.

* Promotions update/create: Address PR comments

This addresses a few small PR comments, removes a TODO, adds a propType,
etc.