Revert "Virtual pages: Enable feature flag in all envs (#70519)" (#70680)
This reverts commit 73a0254f5bf07fb93a48f97944730308087f47f3.

We just found out that when the user is not an Administrator (e.g. Editor), the virtual homepage will fail to load, with the following message in the Console:

ForbiddenError: Sorry, you are not allowed to access the templates on this site.